name: compliance_copilot_mobile
description: Mobile app for Crypto Compliance Copilot - Real-time transaction monitoring and compliance management

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP and API
  http: ^1.1.2
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  
  # Real-time updates
  web_socket_channel: ^2.4.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
  
  # Biometrics
  local_auth: ^2.1.7
  
  # Notifications
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting and analysis
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
